[package]
name = "libman"
version = "0.2.3"
edition = "2018"

[dependencies]
chrono = "0.4.19"
failure = "0.1.8"
itertools = "0.10.1"
regex = "1.5.4"
rspotify = { version = "0.10.0", features = ["blocking"] }
